In [1]:
import numpy as np

In [2]:
path = 'figures/BankHeistNoFrameskip-v4_robust/'

In [3]:
nominal = np.load(path+'nominal.npy')
print(np.mean(nominal))
sem = np.std(nominal)/np.sqrt(np.shape(nominal))
print(sem)

852.0
[7.33484833]


In [4]:
eps = np.load(path + 'fgsm_epsilons.npy')
print(eps)
vals = np.load(path + 'fgsm.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[846.  863.5 854.  502.5]
[ 3.63318042  9.59882805  8.0746517  61.91879763]


In [5]:
eps = np.load(path + 'pgd_epsilons.npy')
print(eps)
vals = np.load(path + 'pgd.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[855. 848. 827.   4.]
[7.29725976 3.84707681 6.00416522 1.78885438]


In [6]:
eps = np.load(path + 'greedy_wc_epsilons.npy')
print(eps)
vals = np.load(path + 'greedy_wc.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[856.  832.5   1.5   0. ]
[10.10940156  4.05431869  0.79843597  0.        ]


In [7]:
eps = np.load(path + 'acr_epsilons.npy')
print(eps)
vals = np.load(path + 'acr.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[0.99955922 0.99091493 0.         0.        ]
[0.00015696 0.00174197 0.         0.        ]


In [8]:
eps = np.load(path + 'action_pert_epsilons.npy')
print(eps)
vals = np.load(path + 'action_pert.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.01 0.02 0.05 0.1 ]
[259.5 146.   54.   45. ]
[21.18342512 15.03994681  6.5345237   6.38357267]
